from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app import store
from app.schemas.envelope import Envelope, Meta, envelope

router = APIRouter(tags=["ai"])


@router.get("/ai-summary/{slug}", response_model=Envelope[dict])
def ai_summary(slug: str) -> Envelope[dict]:
    """A short AI-written read on this stock — technicals, setup pattern, fundamentals
    trend and recent news synthesized into one paragraph. A second opinion alongside
    the rule-based technical verdict, not a replacement for it — a missing artifact
    just means the symbol wasn't in scope that night, or Gemini was unavailable."""
    data = store.ai_summary(slug)
    if not data:
        raise HTTPException(status_code=404, detail=f"No AI summary for {slug!r}.")
    return envelope(data, Meta(**store.meta()))


@router.get("/weekly-outlook", response_model=Envelope[dict])
def weekly_outlook() -> Envelope[dict]:
    """The AI's weekly market-wide call — breadth/volatility/flows/sectors/indices
    synthesized into one direction + sector lean, refreshed Fridays only. Carries a
    self-graded review of its own prior call once mem0 has more than one week on
    record."""
    data = store.weekly_outlook()
    if not data:
        raise HTTPException(
            status_code=503,
            detail="No weekly outlook yet — generated on the first Friday nightly run after this shipped.",
        )
    return envelope(data, Meta(**store.meta()))


@router.get("/results-calendar", response_model=Envelope[dict])
def results_calendar() -> Envelope[dict]:
    """Quarterly result dates, whole market, ±30 days. Upcoming board meetings are
    shown unconditionally; already-filed results only appear if AI judged them good
    from the real filed figures — a bad or not-yet-filed result is simply absent,
    never guessed at or flagged as bad."""
    data = store.results_calendar()
    if not data:
        raise HTTPException(
            status_code=503,
            detail="Artifacts not loaded yet. Run `python -m jobs.run_nightly`.",
        )
    return envelope(data, Meta(**store.meta()))


@router.get("/ai-top-picks", response_model=Envelope[dict])
def ai_top_picks() -> Envelope[dict]:
    """Tonight's top 5 swing setups for the dashboard. Rules gate eligibility (uptrend,
    not stretched or extended, profitable, growing); AI then picks and explains the best
    5 of the shortlist. ``source`` is ``"rules"`` when Gemini was unavailable."""
    data = store.ai_top_picks()
    if not data:
        raise HTTPException(status_code=503, detail="No top picks yet — generated by the nightly run.")
    return envelope(data, Meta(**store.meta()))
