from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app import store
from app.schemas.envelope import Envelope, Meta, envelope

router = APIRouter(tags=["scan"])


@router.get("/daily-scan", response_model=Envelope[dict])
def daily_scan() -> Envelope[dict]:
    """Market regime light + the day's rule-based shortlists: ready-today setups, RS
    leaders, delivery spikes, pocket pivots and sector leaders. No AI involved."""
    data = store.daily_scan()
    if not data:
        raise HTTPException(status_code=503, detail="No daily scan yet — generated by the nightly run.")
    return envelope(data, Meta(**store.meta()))
