from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app import store
from app.schemas.envelope import Envelope, Meta, envelope

router = APIRouter(tags=["scan"])


@router.get("/daily-scan", response_model=Envelope[dict])
def daily_scan() -> Envelope[dict]:
    """Market regime light + the day's rule-based shortlists: ready-today setups, RS
    leaders, delivery spikes, pocket pivots and sector leaders. No AI involved."""
    data = store.daily_scan()
    if not data:
        raise HTTPException(status_code=503, detail="No daily scan yet — generated by the nightly run.")
    return envelope(data, Meta(**store.meta()))


@router.get("/morning-brief", response_model=Envelope[dict])
def morning_brief() -> Envelope[dict]:
    """Pre-market brief built at 8:15 AM IST: global cues, NIFTY levels, stocks in
    focus, overnight announcements, events and a checklist. Numbers from data sources;
    the AI only writes the headline and summary points."""
    data = store.morning_brief()
    if not data:
        detail = "No morning brief yet — built at 8:15 AM IST on trading days."
        raise HTTPException(status_code=503, detail=detail)
    meta = {**store.meta(), "source": "Yahoo Finance + NSE", "as_of": data.get("generated_at")}
    return envelope(data, Meta(**meta))
