"""phase 1 — indicators, indices, fundamentals, scores, saved screens

Revision ID: 96181c3a5d46
Revises: 0001
Create Date: 2026-09-08 21:40:06.431226
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indices')),
    sa.UniqueConstraint('symbol', name=op.f('uq_indices_symbol'))
    )
    op.create_table('saved_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_screens'))
    )
    op.create_index('ix_saved_screens_user', 'saved_screens', ['user_id'], unique=False)
    op.create_table('index_bars',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], name=op.f('fk_index_bars_index_id_indices')),
    sa.PrimaryKeyConstraint('index_id', 'date', name=op.f('pk_index_bars'))
    )
    op.create_index('ix_index_bars_date', 'index_bars', ['date'], unique=False)
    op.create_table('daily_indicators',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ema_20', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('above_sma_20', sa.Boolean(), nullable=True),
    sa.Column('above_sma_50', sa.Boolean(), nullable=True),
    sa.Column('above_sma_200', sa.Boolean(), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('atr_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vol_sma_20', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('rel_volume', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('dist_52w_high_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('dist_52w_low_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('ret_1d', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('ret_5d', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('ret_20d', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('ret_60d', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('ret_120d', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('rs_vs_sector_1m', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('delivery_pct_sma_20', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('delivery_trend', sa.String(length=8), nullable=True),
    sa.Column('indicator_set_version', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_daily_indicators_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('symbol_id', 'date', name=op.f('pk_daily_indicators'))
    )
    op.create_index('ix_daily_indicators_date', 'daily_indicators', ['date'], unique=False)
    op.create_index('ix_daily_indicators_date_dist52wh', 'daily_indicators', ['date', 'dist_52w_high_pct'], unique=False)
    op.create_index('ix_daily_indicators_date_relvol', 'daily_indicators', ['date', 'rel_volume'], unique=False)
    op.create_index('ix_daily_indicators_date_rsi', 'daily_indicators', ['date', 'rsi_14'], unique=False)
    op.create_table('fundamentals',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('debt_equity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('filing_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_fundamentals_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('symbol_id', 'period_end', 'period_type', name=op.f('pk_fundamentals'))
    )
    op.create_table('screener_scores',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('delivery_quality_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_strength_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('earnings_trend_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('inputs_present', sa.SmallInteger(), nullable=False),
    sa.Column('rank_overall', sa.Integer(), nullable=True),
    sa.Column('rank_in_sector', sa.Integer(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('score_version', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_screener_scores_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('symbol_id', 'date', name=op.f('pk_screener_scores'))
    )
    op.create_index('ix_screener_scores_date_composite', 'screener_scores', ['date', 'composite_score'], unique=False)
    op.create_index('ix_screener_scores_date_rank', 'screener_scores', ['date', 'rank_overall'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_screener_scores_date_rank', table_name='screener_scores')
    op.drop_index('ix_screener_scores_date_composite', table_name='screener_scores')
    op.drop_table('screener_scores')
    op.drop_table('fundamentals')
    op.drop_index('ix_daily_indicators_date_rsi', table_name='daily_indicators')
    op.drop_index('ix_daily_indicators_date_relvol', table_name='daily_indicators')
    op.drop_index('ix_daily_indicators_date_dist52wh', table_name='daily_indicators')
    op.drop_index('ix_daily_indicators_date', table_name='daily_indicators')
    op.drop_table('daily_indicators')
    op.drop_index('ix_index_bars_date', table_name='index_bars')
    op.drop_table('index_bars')
    op.drop_index('ix_saved_screens_user', table_name='saved_screens')
    op.drop_table('saved_screens')
    op.drop_table('indices')
    # ### end Alembic commands ###
