"""backtest_runs

Revision ID: 0328ef4c1623
Revises: 0002
Create Date: 2026-09-08 21:47:14.538147
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('benchmark', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('strategy_cagr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('benchmark_cagr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('excess_cagr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beats_benchmark', sa.Boolean(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
