"""pattern_signals

Revision ID: 5c412f2e9a7b
Revises: 0003
Create Date: 2026-09-08 22:11:48.868146
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_signals',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pattern_code', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('pivot_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stop_suggestion', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('target_suggestion', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('base_start_date', sa.Date(), nullable=True),
    sa.Column('base_weeks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('breakout_date', sa.Date(), nullable=True),
    sa.Column('breakout_volume_ratio', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('detector_version', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_pattern_signals_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('symbol_id', 'date', 'pattern_code', name=op.f('pk_pattern_signals'))
    )
    op.create_index('ix_pattern_signals_date_code', 'pattern_signals', ['date', 'pattern_code'], unique=False)
    op.create_index('ix_pattern_signals_date_code_stage', 'pattern_signals', ['date', 'pattern_code', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pattern_signals_date_code_stage', table_name='pattern_signals')
    op.drop_index('ix_pattern_signals_date_code', table_name='pattern_signals')
    op.drop_table('pattern_signals')
    # ### end Alembic commands ###
