"""market context tables

Revision ID: 1c3fa24c42fb
Revises: 0004
Create Date: 2026-09-08 22:20:43.160644
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fii_dii_flows',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('segment', sa.String(length=12), nullable=False),
    sa.Column('fii_buy', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fii_sell', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fii_net', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('dii_buy', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('dii_sell', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('dii_net', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('date', 'segment', name=op.f('pk_fii_dii_flows'))
    )
    op.create_table('holiday_calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('is_muhurat', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_holiday_calendar'))
    )
    op.create_table('market_breadth',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('advances', sa.Integer(), nullable=False),
    sa.Column('declines', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('traded', sa.Integer(), nullable=False),
    sa.Column('pct_above_50dma', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_above_200dma', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_52w_highs', sa.Integer(), nullable=False),
    sa.Column('new_52w_lows', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_market_breadth'))
    )
    op.create_table('index_constituents',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], name=op.f('fk_index_constituents_index_id_indices')),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_index_constituents_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('index_id', 'symbol_id', name=op.f('pk_index_constituents'))
    )
    op.create_index('ix_index_constituents_symbol', 'index_constituents', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_constituents_symbol', table_name='index_constituents')
    op.drop_table('index_constituents')
    op.drop_table('market_breadth')
    op.drop_table('holiday_calendar')
    op.drop_table('fii_dii_flows')
    # ### end Alembic commands ###
